name: ts-forecast
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.9
    - mlflow=2.12.2
    - pymongo=4.6.3
    - pandas
    - numpy
    - boto3==1.34.82
    - pip
    - pip:
      - click==8.1.7
      - darts==0.29.0