apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: "tsops-dev"
secrets:
- name: s3creds

---

apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mlflow-wine-classifier"
  namespace: "tsops-dev"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/0/d11f1571679b4e8c90fd7f805e5e444e/artifacts/model"


        