apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-db-pv
  namespace: tsops-dev
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mlflow-db-pv/
  storageClassName: mlflow-db-storage
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  namespace: tsops-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mlflow-db-storage

---

apiVersion: v1
kind: Service
metadata:
  name: mlflow-db-svc
  namespace: tsops-dev
spec:
  selector:
    app: mlflow-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-db
  namespace: tsops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-db
  template:
    metadata:
      labels:
        app: mlflow-db
    spec:
      containers:
      - name: mlflow-db
        image: mysql/mysql-server@sha256:5b40d96b11333570143d98d3a74100fefadb9abb17b27a95dbc9ad33544ec142
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: dbdata
          mountPath: /var/lib/mysql
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata