apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: tsops-dev
type: Opaque
data:
  MINIO_ACCESS_KEY: <base64 encoded MINIO_ACCESS_KEY>  
  MINIO_SECRET_KEY: <base64 encoded MINIO_SECRET_KEY>  