name: api-tsops
channels:
    - conda-forge
dependencies:
    - uvicorn=0.29.0
    - fastapi=0.110.2
    - pydantic=2.7.1
    - pymongo=4.6.3
    - multi-part=0.0.9
    - pandas==2.2.2
    - pip
    - pip:
        - friendlywords==1.1.3
